app = "https-upgrader-fly"  # заменишь на своё имя приложения на fly.io

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]
